version: '3.3'

services:
  miopen-docker:
    image: miopen-docker
    hostname: miopen
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    security_opt:
      - "seccomp:unconfined"
    environment:
      - ID=${ID}
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/amdgpu:/opt/amdgpu:rw
      - ./home:/home
